name: CI
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  PRISMA_HIDE_UPDATE_MESSAGE: 'true'

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@81f119483401ffde8275edf4c089b42e24b92cf4 # v0.14.0
    with:
      number-of-agents: 3
      # NOTE: Here we are using the special `nx-cloud record` command to ensure that any commands we run that do not go through the cloud task runner natively
      # (i.e. anything that starts with `nx run`/`nx run-many`/`nx affected --target`), are still captured in the Nx Cloud UI and Github App comment for
      # easier troubleshooting. See more here: https://nx.dev/nx-cloud/set-up/record-commands#recording-non-nx-commands
      parallel-commands: |
        npx nx-cloud record -- npx nx format:check
      parallel-commands-on-agents: |
        npx nx affected --target=lint --parallel=3
        npx nx affected --target=test --parallel=3 --ci --code-coverage
        npx nx affected --target=build --parallel=3
      artifacts-path: dist/
      artifacts-name: dist-artifacts

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@81f119483401ffde8275edf4c089b42e24b92cf4 # v0.14.0
    with:
      number-of-agents: 3

  docker-build:
    needs: main
    runs-on: ubuntu-latest
    env:
      INPUT_PUSH: true
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@2b51285047da1547ffb1b2203d8be4c0af6b1f20 # v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@0e2d18b530b83b68263ff7b74e46b1ba300c83fc # v3
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      - name: 'Downloading artifacts'
        continue-on-error: true
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
        with:
          name: dist-artifacts
          path: dist
      - run: npm install
      - run: npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=container --parallel=2
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_NEST_APP_IMAGES: ghcr.io/gperdomor/nx-container-sandbox/nest-app-with-docker
          INPUT_NEXT_APP_IMAGES: ghcr.io/gperdomor/nx-container-sandbox/next-app-with-docker
          INPUT_REACT_APP_IMAGES: ghcr.io/gperdomor/nx-container-sandbox/react-app-with-docker

  podman-build:
    needs: main
    runs-on: ubuntu-latest
    env:
      INPUT_PUSH: true
      INPUT_ENGINE: podman
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 0
      - name: Login to GitHub Container Registry
        run: echo "${{ github.token }}" | podman login -u ${{ github.actor }} --password-stdin ghcr.io/${{ github.repository_owner }}
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@0e2d18b530b83b68263ff7b74e46b1ba300c83fc # v3
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      - name: 'Downloading artifacts'
        continue-on-error: true
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
        with:
          name: dist-artifacts
          path: dist
      - run: npm install
      - run: npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=container --parallel=2
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_NEST_APP_IMAGES: ghcr.io/gperdomor/nx-container-sandbox/nest-app-with-podman
          INPUT_NEXT_APP_IMAGES: ghcr.io/gperdomor/nx-container-sandbox/next-app-with-podman
          INPUT_REACT_APP_IMAGES: ghcr.io/gperdomor/nx-container-sandbox/react-app-with-podman
